### ISSUE TITLE
introduce Appveyor CI for Windows

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#29]

**Comment by tnagler** [comment]
Any volunteers, @slayoo? ;)

**Comment by slayoo** [comment]
Yes, I'll try to fight with it

**Comment by slayoo** [comment]
For the record, I've started it here: https://github.com/slayoo/vinecopulib/pull/1

**Comment by slayoo** [comment]
For the record: some progress made but now I'm blocked by the issue of not having .lib files for R (only .dlls are shipped in the binary package). As discussed here: http://cmake.3232098.n2.nabble.com/FindLibrary-only-looks-for-lib-under-Windows-td5532822.html CMake only looks for .lib files on Windows

**Comment by tnagler** [comment]
I need some context. Why do you need the lib of an R package and which package is it?

**Comment by slayoo** [comment]
findR.cmake uses find_library to find libR.so on Linux, libR.dylib on OSX and ... R.lib on Windows, but the Windows R installer only installs R.dll

**Comment by slayoo** [comment]
Besides the above R problem, other issues soved: https://ci.appveyor.com/project/slayoo/vinecopulib/build/1.0.43

**Comment by slayoo** [comment]
Was merged yesterday
