### ISSUE TITLE
ASAN-reported error in test_bicop_select on travis

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#31]
https://travis-ci.org/tvatter/vinecopulib/builds/196939374#L7384

**Comment by slayoo** [comment]
Trying to reproduce the error on a local machine (with no success) I've noticed that the Travis log mentions something very fishy:

```
#1 0x55eb0015a0f0 in Eigen::internal::BlockImpl_dense<Eigen::Matrix<double, -1, -1, 0, -1, -1>, -1, 1, true, true>::BlockImpl_dense(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, long)
 /usr/include/eigen3/Eigen/src/Core/Block.h:355
#2 0x55eb00159c82 in Eigen::BlockImpl<Eigen::Matrix<double, -1, -1, 0, -1, -1>, -1, 1, true, Eigen::Dense>::BlockImpl(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, long) 
 /usr/lib/R/library/RcppEigen/include/Eigen/src/Core/Block.h:157
```

Notice the two different Eigen include paths! One seems to be the system Eigen, the other is the one from RcppEigen.

**Comment by slayoo** [comment]
And on Ubuntu zesty, these versions indeed differ:

```
$ fgrep VERSION /usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/util/Macros.h | head -3
#define EIGEN_WORLD_VERSION 3
#define EIGEN_MAJOR_VERSION 2
#define EIGEN_MINOR_VERSION 9

$ fgrep VERSION /usr/include/Eigen/src/Core/util/Macros.h | head -3
#define EIGEN_WORLD_VERSION 3
#define EIGEN_MAJOR_VERSION 3
#define EIGEN_MINOR_VERSION 2
```

**Comment by tnagler** [comment]
I tried looking into this yesterday. I also cannot reproduce the error locally, so I have to try to find the bug via travis. I'm not sure whether the different Eigen versions are the problem, though.  I narrowed the error down to the lines 
```cpp
    const Eigen::Map<VecXd> U1 = Rcpp::as<Eigen::Map<VecXd>>(R.parseEval(u1));
    const Eigen::Map<VecXd> U2 = Rcpp::as<Eigen::Map<VecXd>>(R.parseEval(u2));
    U_.col(0) = U1;
    U_.col(1) = U2;
```
in `/test/src_test/r_instance.cpp`. The error occurs when ` U_.col(0) = U1;` is called. I'll try to find out what's wrong exactly.

**Comment by slayoo** [comment]
Compiling vinecopulib with the RcppEigen Eigen headers solves the problem:
https://github.com/tvatter/vinecopulib/pull/30/commits/2802aa94c80e4015719a08784989ad05e0b93701
https://travis-ci.org/tvatter/vinecopulib/builds/197268081

**Comment by tnagler** [comment]
Hmm, that's really strange. Your solution isn't nice, but OK for now I guess. Let's check again as soon [RcppEigen has updated to 3.3.2](https://github.com/RcppCore/RcppEigen/issues/41).

**Comment by tvatter** [comment]
It's a bit hacky indeed ;)

Also, shouldn't EIGEN3_INCLUDE_DIR be defined using RCPPEIGEN_INCLUDE_DIR in findR.cmake?

**Comment by slayoo** [comment]
This would introduce the hacky logic into the project, while now it only lives in the travis.yml file...
Also, I don't really see the reason it should be strange or hacky... we are only pointing the build to a compatible version of the headers. Having it inside findR.cmake would indeed be hacky, though.

**Comment by tvatter** [comment]
I think that introducing this logic into the project is not a good idea, since we will remove the R dependencies altogether at some point. Actually, have we finally reached this point? In the end, it's simply about writing unit tests that do not require the dependencies. We already discussed a way to implement this with Thomas, we just need to find the time to do that!

**Comment by slayoo** [comment]
If I understand correctly, we can then close this issue - the R-dependency is the topic of https://github.com/tvatter/vinecopulib/issues/20
