### ISSUE TITLE
gtest policy CMP0048

### ISSUE THREAD

**Issue by tvatter** [tvatter/vinecopulib#78]
When running cmake, you may have noticed the following warning:

`Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.`

[This is a known issue of gtest](https://github.com/google/googletest/issues/709) and I don't really know what we can do about it.

**Comment by tnagler** [comment]
Then let's just tolerate it until it's fixed in gtest. Nothing we can do, really.

**Comment by tvatter** [comment]
I would like to keep the issue open as a reminder if that's OK with you ;)

**Comment by tnagler** [comment]
I thoght it's enough to see it in cmake directly ;)

**Comment by tvatter** [comment]
See PR #97
