### ISSUE TITLE
boost ver requirement?

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#79]
Python bindings do not require Boost 1.63 anymore (since we use NumPy C bindings instead of the Boost.NumPy).

Should we relax the requirement in cmake/findDependencies.cmake?
(I remember that there was something requireing a recent version in the C++ vinecopulib code, but I don't remember what it was and what the version was)

Finally, if 1.63 is not required, perhaps we can skip the Ubuntu update in travis?

**Comment by tvatter** [comment]
1. Concerning relaxing the requirement: Thomas suggested the same at some point. However, when he tried to change the requirement and compile the library with an older version (and without the Python bindings), it didn't work, so we stuck with 1.63. Any way you could check which version is required and update this?

2. Concerning skiping the Ubuntu update: it 1.63 is not required, sure!

**Comment by tnagler** [comment]
There was a bug in the minimum spanning tree [until boost 1.54](https://svn.boost.org/trac/boost/ticket/9012). Anything after that should work (although I thought that I had 1.55 when I found the bug, so we may need to try a few version).

**Comment by tnagler** [comment]
I checked this now, 1.55 is not working but everything since 1.56 does. If The python bindings don't require a particular version, I suggest we lower the requirements 1.56.

**Comment by tnagler** [comment]
I changed it in c802b15bd451ba45d2f2b31c86e8ad845fbea4c7. Unfortunately, [Ubuntu trusty does not distribute versions larger than 1.54](https://launchpad.net/ubuntu/trusty/+package/libboost-dev), so I didn't change the travis setup.
