### ISSUE TITLE
should the binaries be placed within "build" directory?

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#80]
Currently, the binaries are placed outside of the build directory, what is - in my opinion - counterintuitive (i.e., not the default bahaviouor CMake used in most (all) projects I've tried). It is also not possible to generate several builds not overwriting the binaries, e.g.:

- build-O3
- build-Ofast
- build-debug
- ...

If a user wants to put the binaries in "vinecopulib/bin" this would still be possible by setting CMAKE_PREFIX_PATH and doing "make install"

What about placing the binaries within "build"?

**Comment by tvatter** [comment]
Fine by me. The current path is a relic from the CMake skeleton project I used.

**Comment by tnagler** [comment]
Yeah. I'd prefer having them in /build.

**Comment by tvatter** [comment]
Done!
