### ISSUE TITLE
build failure on clean-up branch with gcc 6.3

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#88]
https://github.com/tvatter/vinecopulib/blob/clean-up/src/bicop/indep.cpp#L53

```
/home/vagrant/devel/vinecopulib/src/bicop/indep.cpp: In member function ‘virtual Eigen::MatrixXd vinecopulib::IndepBicop::tau_to_parameters(const double&)’:
/home/vagrant/devel/vinecopulib/src/bicop/indep.cpp:53:31: error: call of overloaded ‘Matrix(int)’ is ambiguous
         Eigen::VectorXd pars(0);
```

**Comment by tvatter** [comment]
I do not understand the error message. Should we replace `Eigen::VectorXd pars(0);` by `Eigen::MatrixXd pars(0,0);` ?

**Comment by tnagler** [comment]
I noticed the same in the R-interface, `return Eigen::VectorXd();` will do the job.

**Comment by slayoo** [comment]
But what's the purpose of this method there?
If it's just something that must be overloaded, perhaps it's better to throw std::logic_error() ?

**Comment by tnagler** [comment]
The independence copula has no parameters. This is consistently represented by an empty matrix throughout the library.

**Comment by tvatter** [comment]
See 6a40e6d

**Comment by slayoo** [comment]
confirm, this helped
